version: "3.9"
services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_DB: "onlinestoredb"
      POSTGRES_USER: "meyster"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
