app-config:
  is-debug: false
  is-development: false
  log-level: trace
  admin-user:
    email: "admin@admin.ru"
    password: "admin"

http:
  http_ip: 0.0.0.0
  http_port: 8000
  cors:
    allowed-methods: [ "GET", "POST", "PUT", "PATCH", "OPTIONS", "DELETE" ]
    allowed-origins:
      - "*"
    allow-credentials: true
    allowed-headers:
      - "Authorization"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    options-passthrough: true
    exposed-headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"
    debug: true

grpc:
  grpc_ip: 0.0.0.0
  grpc_port: 8001

postgre-sql:
  username: "meyster"
  password: "postgres"
  host: 0.0.0.0
  port: 5432
  database: "onlinestoredb"
